import { createFileRoute } from '@tanstack/react-router';
import { AudioLines, BookOpen, Braces, Check, Film, Headphones, Menu, Mic2, MoveUpRight, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { VoicePreview } from '@/components/voice-preview';
import actorImage from '@/assets/voicefy/voice-actor.jpg';
import podcastImage from '@/assets/voicefy/podcast.jpg';
import bookImage from '@/assets/voicefy/audiobook.jpg';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'Voicefy AI — Text to Speech in English, Bengali & Hindi' },
    { name: 'description', content: 'Meet Voicefy AI. A premium text-to-speech experience designed for 400+ voices in English, Bengali, and Hindi, with a developer-first speech API.' },
    { property: 'og:title', content: 'Voicefy AI — Give your words a voice' },
    { property: 'og:description', content: 'Your stories. Three languages. 400+ voices. Discover a new way to create with Voicefy AI.' },
    { property: 'og:type', content: 'website' },
    { name: 'twitter:card', content: 'summary_large_image' },
  ] }), component: Index,
});

function Logo() { return <a className="mc-logo vf-logo" href="#" aria-label="Voicefy AI home"><AudioLines aria-hidden="true" />Voicefy<span>AI</span></a>; }
function Cta({ children = 'Try a voice', outline = false, href = '#voice-studio' }: { children?: string; outline?: boolean; href?: string }) {
  return <Button asChild variant={outline ? 'outline' : 'default'} className={`mc-pill ${outline ? 'mc-outline' : ''}`}><a href={href}>{children}<MoveUpRight size={13} /></a></Button>;
}
function Heading({ title, copy }: { title: string; copy: string }) { return <div className="mc-section-heading"><h2>{title}</h2><p>{copy}</p></div>; }
const features = [
  { title: 'Text in. Magic out.', kicker: 'A voice for every idea', points: ['Turn scripts, captions, and ideas into spoken stories', 'Find your sound in a catalog of 400+ voices', 'Make every word feel like it belongs to your brand'], image: actorImage, alt: 'Voice artist beside a professional studio microphone', label: 'THE VOICE BEHIND YOUR NEXT BIG IDEA', overlay: 'Warm. Confident. Unmistakably you.' },
  { title: 'Three languages. Zero boundaries.', kicker: 'English · বাংলা · हिंदी', points: ['Speak to your audience in English, Bengali, or Hindi', 'Keep the meaning, rhythm, and personality of your words', 'Create local stories with a world-class sound'], image: podcastImage, alt: 'South Asian narrator recording in a blue-lit podcast studio', label: 'CONNECT IN THEIR LANGUAGE', overlay: 'Hello. হ্যালো. नमस्ते. A little closer to your audience.' },
  { title: 'Make every story worth listening to.', kicker: 'From the first word to the last', points: ['Bring a distinctive voice to audiobooks and podcasts', 'Give lessons and explainers a clear, engaging delivery', 'Explore the sound that fits your next production'], image: bookImage, alt: 'Audiobook narrator reading into a recording microphone', label: 'WORDS THAT COME ALIVE', overlay: 'Once upon a time, a great story found its voice.' },
];
const useCases = [
  { title: 'Videos', text: 'A memorable voice for every reel, film, and explainer.', icon: Film },
  { title: 'Podcasts', text: 'Set the tone for stories people want to keep hearing.', icon: Headphones },
  { title: 'Audiobooks', text: 'Give every chapter a little more character.', icon: BookOpen },
  { title: 'Apps & products', text: 'Put a voice at the heart of your digital experience.', icon: Braces },
];
const faqs = [
  ['What is Voicefy AI?', 'Voicefy AI is a text-to-speech product focused on turning written content into natural-sounding voiceovers. This page introduces the product and includes a browser-powered audio preview.'],
  ['Which languages does Voicefy support?', 'Voicefy is designed for English, Bengali, and Hindi only. The preview uses voices installed on your device, so availability varies by browser and operating system.'],
  ['Are there really 400+ voices?', 'The planned Voicefy catalog includes 400+ voices. The full catalog is not connected to this preview yet; the available preview voices come from your device.'],
  ['Can I use Voicefy in my app through an API?', 'A developer API is part of the Voicefy product offering. The API section here is a concept preview, not a live endpoint. API access, authentication, and documentation will be available when the service is connected.'],
  ['Can I download the audio or use it commercially?', 'This browser preview does not offer audio downloads. Export formats, pricing, and commercial licensing will be confirmed when the Voicefy generation service is available.'],
];

function Index() {
  return <div className="mc-page">
    <header className="mc-header"><Logo /><nav className="mc-nav" aria-label="Main navigation"><a href="#features">Product</a><a href="#voices">Voices</a><a href="#use-cases">Use cases</a><a href="#api">API</a><a href="#faq">FAQs</a></nav><div className="mc-nav-actions"><Button asChild variant="ghost" className="mc-header-cta"><a href="#voice-studio">Try a voice ↗</a></Button></div><details className="mc-mobile-menu"><summary className="mc-mobile-toggle" aria-label="Toggle menu"><Menu size={22} /></summary><nav className="mc-mobile-links" aria-label="Mobile navigation"><a href="#features">Product</a><a href="#voices">Voices</a><a href="#use-cases">Use cases</a><a href="#api">API</a><a href="#faq">FAQs</a></nav></details></header>
    <main>
      <section className="mc-hero vf-hero"><div className="mc-hero-copy mc-container"><div className="vf-eyebrow"><Sparkles size={13} /> WORDS TO VOICE. BEAUTIFULLY.</div><h1>Voicefy AI<br /><span>Sound more human.</span></h1><p>Give your words a voice worth listening to. Premium text to speech in English, Bengali, and Hindi. Your story. Your sound.</p><Cta /><div className="vf-hero-proof"><span>400+ voices</span><i /><span>3 languages</span><i /><span>Endless stories</span></div></div><div className="mc-hero-stage vf-hero-stage"><div className="vf-floating vf-float-left"><span className="vf-mini-icon"><Mic2 size={18} /></span><div><strong>Made to sound human</strong><small>A little more feeling. A lot more you.</small></div></div><VoicePreview /><div className="vf-floating vf-float-right"><Check size={18} /><div><strong>One story. Three languages.</strong><small>English · বাংলা · हिंदी</small></div></div></div></section>
      <section className="mc-section mc-assistant mc-container" id="voices"><Heading title="Your always-on voice studio" copy="Less recording. More creating. All the personality." /><div className="mc-assistant-grid"><article className="mc-assistant-item"><div className="mc-assistant-visual vf-benefit-photo"><img src={actorImage} alt="Voice artist in a recording studio" loading="lazy" width={1200} height={1008} /><div className="vf-photo-badge"><AudioLines size={18} /> 400+ voices. One perfect fit.</div></div><h3>A voice for every vibe</h3><p>Warm and conversational. Bold and cinematic. A rich voice catalog designed to make your content unmistakable.</p></article><article className="mc-assistant-item"><div className="mc-assistant-visual"><div className="vf-language-art"><span>Hello.</span><span>হ্যালো.</span><span>नमस्ते.</span><small>THREE LANGUAGES. REAL CONNECTION.</small></div></div><h3>Closer in every language</h3><p>English, Bengali, and Hindi. Tell your story in the language your audience thinks, feels, and lives in.</p></article><article className="mc-assistant-item"><div className="mc-assistant-visual"><div className="vf-sound-art"><AudioLines size={100} strokeWidth={1.1} /><span>Ideas → audio</span><small>LET YOUR WORDS DO THE TALKING</small></div></div><h3>Create at your own pace</h3><p>From a quick voiceover to a whole new story, make room for more creativity and fewer recording sessions.</p></article></div><div className="mc-centered-cta"><Cta /></div></section>
      <section className="mc-section mc-features mc-container" id="features"><Heading title="Better voices. Bigger possibilities." copy="Made for the creators, storytellers, and builders in you." />{features.map(feature => <article className="mc-feature" key={feature.title}><div className="mc-feature-copy"><h3>{feature.title}</h3><p className="mc-kicker">{feature.kicker}</p><ul>{feature.points.map(point => <li key={point}>{point}</li>)}</ul></div><div className="mc-feature-image"><img src={feature.image} alt={feature.alt} loading="lazy" width={1200} height={1008} /><div className="mc-feature-overlay"><small><Sparkles size={13} /> {feature.label}</small>{feature.overlay}</div></div></article>)}</section>
      <section className="mc-section mc-platforms mc-container" id="use-cases"><Heading title="Wherever your story takes you" copy="One voice studio. A whole world of things to create." /><div className="mc-platform-grid">{useCases.map(({ title, text, icon: Icon }) => <a className="mc-platform" href="#voice-studio" key={title}><Icon className="vf-use-icon" size={36} strokeWidth={1.4} /><h3>{title}</h3><p>{text}</p><span>Explore a voice ↗</span></a>)}</div></section>
      <section className="mc-section mc-container" id="api"><Heading title="Your product. Our voice." copy="A developer-first speech API, designed to fit right into your workflow." /><div className="vf-api-grid"><div className="mc-feature-copy"><div className="vf-eyebrow"><Braces size={16} /> BUILT FOR BUILDERS</div><h3>Great sound.<br />Less complexity.</h3><ul><li>Text-to-speech for your apps and creative workflows</li><li>English, Bengali, and Hindi voice experiences</li><li>400+ voices to match your product’s personality</li></ul><p className="vf-api-status">API access is coming with the connected Voicefy service.</p><Cta href="#faq" outline>API details</Cta></div><div className="vf-code-panel"><div className="vf-code-top"><span><Braces size={16} /> Voicefy API</span><span>CONCEPT PREVIEW</span></div><pre><code><span className="vf-code-muted">// A simpler way to speak</span>{'\n'}<span className="vf-code-key">const</span>{' audio = await voicefy.speech.create({\n'}{'  text: '}<span className="vf-code-string">"Hello, world."</span>{',\n  language: '}<span className="vf-code-string">"en"</span>{',\n  voice: '}<span className="vf-code-string">"your-selected-voice"</span>{'\n});'}</code></pre><div className="vf-code-bottom"><AudioLines size={22} /><span>Your next great voice experience.</span></div></div></div></section>
      <section className="mc-section mc-container"><Heading title="Skip the retakes. Keep the feeling." copy="More time for the story. Less time in the recording booth." /><div className="mc-compare-grid"><div className="mc-compare-panel"><span>The old way:</span><h3>All setup.<br />So many retakes.</h3><ul><li>Finding the right voice for every project</li><li>Scheduling studios and recording sessions</li><li>Re-recording when one sentence changes</li><li>Starting from scratch for each language</li></ul><Cta /></div><div className="mc-compare-panel after"><span>The Voicefy way:</span><h3>More stories.<br />Less friction.</h3><ul><li>A voice catalog built for your creativity</li><li>Your ideas, ready for a new sound</li><li>A text-first workflow made for changes</li><li>English, Bengali, and Hindi in one place</li></ul><Cta /></div></div></section>
      <section className="mc-section mc-container"><Heading title="From words to wow." copy="Your next voiceover starts with a little inspiration." /><div className="mc-steps"><div className="mc-step"><span>01 / 03</span><h3>Bring your words</h3><p>A script, a story, or your next big idea.</p></div><div className="mc-step"><span>02 / 03</span><h3>Find your voice</h3><p>Choose your language. Explore your sound.</p></div><div className="mc-step"><span>03 / 03</span><h3>Hear the difference</h3><p>Preview the words. Feel the possibility.</p></div></div><div className="mc-steps-actions"><Cta /><Cta href="#api" outline>Explore API</Cta></div></section>
      <section className="mc-final-cta vf-final-cta"><img src={actorImage} alt="Voicefy voice artist at a studio microphone" loading="lazy" width={1200} height={1008} /><div className="mc-final-copy"><div className="vf-eyebrow">THIS IS YOUR MOMENT</div><h2>Give your words<br />a real voice.</h2><p>400+ voices. English, Bengali, and Hindi. A world of stories waiting to be heard.</p><Cta /></div></section>
      <section className="mc-section mc-container" id="faq"><div className="mc-faq"><div className="mc-section-heading"><h2>A little more clarity.</h2></div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    </main>
    <footer className="mc-footer"><div className="mc-container"><div className="mc-footer-top"><div><Logo /><p className="vf-footer-tagline">Words to voice. Beautifully.</p></div><div className="mc-footer-columns"><div className="mc-footer-column"><span>Voicefy</span><a href="#features">Text to speech</a><a href="#voices">Voice collection</a><a href="#api">Developer API</a></div><div className="mc-footer-column"><span>Create</span><a href="#use-cases">Videos & podcasts</a><a href="#use-cases">Audiobooks</a><a href="#use-cases">Apps & products</a></div><div className="mc-footer-column"><span>Explore</span><a href="#voice-studio">Voice preview</a><a href="#faq">FAQs</a><a href="#voices">Languages</a></div></div></div><div className="mc-footer-bottom"><span>© 2026 Voicefy AI</span><span>English · বাংলা · हिंदी</span></div></div></footer>
  </div>;
}
